<?php
if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_62b07b640efb1',
        'title' => 'Multi page builder',
        'fields' => array(
            array(
                'key' => 'field_62b07f5466759',
                'label' => 'Multi page builder',
                'name' => 'multi_page_builder',
                'type' => 'flexible_content',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layouts' => array(
                    'layout_62b07f81c3315' => array(
                        'key' => 'layout_62b07f81c3315',
                        'name' => 'multibox_layout_clone',
                        'label' => 'Multi Box Layout',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b07fb0f4766',
                                'label' => 'Multi Box Repeter',
                                'name' => 'multi_boxes_repeter_clone',
                                'type' => 'clone',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'clone' => array(
                                    0 => 'field_62ab282e941af',
                                ),
                                'display' => 'seamless',
                                'layout' => 'block',
                                'prefix_label' => 0,
                                'prefix_name' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b08902f9ee6' => array(
                        'key' => 'layout_62b08902f9ee6',
                        'name' => 'expanded_text_layout',
                        'label' => 'expanded text',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b0898df9ee8',
                                'label' => 'Extended Text Section',
                                'name' => 'expanded_text_section',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_62b089bef9ee9',
                                        'label' => 'title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '70',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_62b08a4bf9eec',
                                        'label' => 'title class',
                                        'name' => 'titleClass',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_62b089caf9eea',
                                        'label' => 'content',
                                        'name' => 'content',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                    array(
                                        'key' => 'field_62b0891ef9ee7',
                                        'label' => 'Color backgound',
                                        'name' => 'bgColor',
                                        'type' => 'color_picker',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '#000000',
                                        'enable_opacity' => 0,
                                        'return_format' => 'string',
                                    ),
                                    array(
                                        'key' => 'field_62b089ddf9eeb',
                                        'label' => 'Select text color',
                                        'name' => 'textColor',
                                        'type' => 'select',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '50',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'choices' => array(
                                            'light' => 'Light',
                                            'dark' => 'Dark',
                                        ),
                                        'default_value' => false,
                                        'allow_null' => 0,
                                        'multiple' => 0,
                                        'ui' => 0,
                                        'return_format' => 'value',
                                        'ajax' => 0,
                                        'placeholder' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b0971920197' => array(
                        'key' => 'layout_62b0971920197',
                        'name' => 'simply_html_layout',
                        'label' => 'Simply HTML Editor',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b0972e20198',
                                'label' => 'simply_html_block',
                                'name' => 'simply_html_block',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_62b0973e20199',
                                        'label' => 'editor html',
                                        'name' => 'html',
                                        'type' => 'wysiwyg',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'tabs' => 'all',
                                        'toolbar' => 'full',
                                        'media_upload' => 1,
                                        'delay' => 0,
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b1a2b6f3206' => array(
                        'key' => 'layout_62b1a2b6f3206',
                        'name' => 'simply_slider_layout',
                        'label' => 'Slider',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b1a2d0f3207',
                                'label' => 'Slider',
                                'name' => 'simplySlider',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'collapsed' => '',
                                'min' => 0,
                                'max' => 0,
                                'layout' => 'table',
                                'button_label' => '',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_62b1a330f3208',
                                        'label' => 'image',
                                        'name' => 'image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '30',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'preview_size' => 'medium',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_62b1a33ef3209',
                                        'label' => 'description',
                                        'name' => 'description',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '70',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b1ecea223ec' => array(
                        'key' => 'layout_62b1ecea223ec',
                        'name' => 'activities_slider_layout',
                        'label' => 'Activities slider',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b1ed01223ed',
                                'label' => 'Activities Section',
                                'name' => 'activitiesSection',
                                'type' => 'clone',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'clone' => array(
                                    0 => 'field_62a8a76d83598',
                                ),
                                'display' => 'seamless',
                                'layout' => 'block',
                                'prefix_label' => 0,
                                'prefix_name' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b2da01bc2ee' => array(
                        'key' => 'layout_62b2da01bc2ee',
                        'name' => 'text_block_with_bg_image_layout',
                        'label' => 'Text block with background image',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b2da34bc2ef',
                                'label' => 'Text block with backgroung image',
                                'name' => 'text_block_with_bg_image',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_62b2da98bc2f0',
                                        'label' => 'bg_image',
                                        'name' => 'bg_image',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'preview_size' => 'full',
                                        'library' => 'all',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                    ),
                                    array(
                                        'key' => 'field_62b2daa6bc2f1',
                                        'label' => 'title',
                                        'name' => 'title',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '20',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'maxlength' => '',
                                    ),
                                    array(
                                        'key' => 'field_62b2dab0bc2f2',
                                        'label' => 'content',
                                        'name' => 'content',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '60',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'placeholder' => '',
                                        'maxlength' => '',
                                        'rows' => 8,
                                        'new_lines' => '',
                                    ),
                                ),
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b2dea772464' => array(
                        'key' => 'layout_62b2dea772464',
                        'name' => 'timeline_layout',
                        'label' => 'Timeline',
                        'display' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_62b2deba72465',
                                'label' => 'timeline',
                                'name' => 'timeline_builder',
                                'type' => 'clone',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'clone' => array(
                                    0 => 'group_62b0765d0287e',
                                ),
                                'display' => 'seamless',
                                'layout' => 'block',
                                'prefix_label' => 0,
                                'prefix_name' => 0,
                            ),
                        ),
                        'min' => '',
                        'max' => '',
                    ),
                    'layout_62b2e02733e51' => array(
                        'key' => 'layout_62b2e02733e51',
                        'name' => 'empty_space',
                        'label' => 'Empty space',
                        'display' => 'block',
                        'sub_fields' => array(),
                        'min' => '',
                        'max' => '',
                    ),
                ),
                'button_label' => 'Aggiungi Riga',
                'min' => '',
                'max' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                ),
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'homepage.php',
                ),
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'contact-page.php',
                ),
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'blocklist-page.php',
                ),
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'category-page.php',
                ),
                array(
                    'param' => 'post_template',
                    'operator' => '!=',
                    'value' => 'product-page.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;
